### ISSUE TITLE
Please, change {PV} in  Spotify Gentoo Ebuild

### ISSUE THREAD

**Issue by ghost** [AlbertVeli/Spotify-Overlay#3]
Hi, look at http://repository.spotify.com/pool/non-free/s/spotify-client/

{PV} must be 72, not 70.

Please update Gentoo Ebuild. Thanks

**Comment by AlbertVeli** [comment]
Hi, you should use the official gentoo ebuild:

https://packages.gentoo.org/packages/media-sound/spotify

and not this one that I put on github a long time ago, it is not updated. Is the same error in the official gentoo ebuild? It should not be, in that case contact the maintaner Matthew Thode <prometheanfire@gentoo.org> and ask him to fix it.

Regards,

Albert

**Comment by ghost** [comment]
Omg, sorry for dismiss. You can close this disscussion if you want. I've made bug report
https://bugs.gentoo.org/649020
